/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'imageUrl' : IDL.Text,
  'publicationDate' : IDL.Text,
  'excerpt' : IDL.Text,
});

export const idlService = IDL.Service({
  'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'saveArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'imageUrl' : IDL.Text,
    'publicationDate' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  
  return IDL.Service({
    'getArticle' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'saveArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };